<a href="https://colab.research.google.com/github/sreebalajisree/python_handson/blob/main/extractedText_deviceinfo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install easyocr

Requirement already satisfied: easyocr in /usr/local/lib/python3.7/dist-packages (1.4.1)
Requirement already satisfied: Pillow<8.3.0 in /usr/local/lib/python3.7/dist-packages (from easyocr) (7.1.2)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.7/dist-packages (from easyocr) (4.5.5.64)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from easyocr) (3.13)
Requirement already satisfied: torch in /usr/local/lib/python3.7/dist-packages (from easyocr) (1.10.0+cu111)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.7/dist-packages (from easyocr) (0.18.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from easyocr) (1.4.1)
Requirement already satisfied: python-bidi in /usr/local/lib/python3.7/dist-packages (from easyocr) (0.4.2)
Requirement already satisfied: torchvision>=0.5 in /usr/local/lib/python3.7/dist-packages (from easyocr) (0.11.1+cu111)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from easyocr) (1.21.5)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch->easyocr) (3.10.0.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from python-bidi->easyocr) (1.15.0)
Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image->easyocr) (2.4.1)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.7/dist-packages (from scikit-image->easyocr) (2021.11.2)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image->easyocr) (2.6.3)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image->easyocr) (3.2.2)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from scikit-image->easyocr) (1.3.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->easyocr) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->easyocr) (1.4.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->easyocr) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->easyocr) (0.11.0)

In [7]:
!pip install opencv-python-headless==4.1.2.30

Collecting opencv-python-headless==4.1.2.30
  Downloading opencv_python_headless-4.1.2.30-cp37-cp37m-manylinux1_x86_64.whl (21.8 MB)
     |████████████████████████████████| 21.8 MB 2.4 MB/s
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/dist-packages (from opencv-python-headless==4.1.2.30) (1.21.5)
Installing collected packages: opencv-python-headless
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.5.5.64
    Uninstalling opencv-python-headless-4.5.5.64:
      Successfully uninstalled opencv-python-headless-4.5.5.64
Successfully installed opencv-python-headless-4.1.2.30

In [8]:
import easyocr
import cv2

In [9]:
# Load the google drive
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [12]:
reader = easyocr.Reader(['en'])
output = reader.readtext("/content/device_info1.jpg")
output

CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.

[([[25, 13], [223, 13], [223, 55], [25, 55]], 'SMAREDTV', 0.5913040883835136),
 ([[973, 17], [1173, 17], [1173, 55], [973, 55]],
  'XOverABR',
  0.9995070422733559),
 ([[1794, 20], [1822, 20], [1822, 46], [1794, 46]], '0', 0.9771506309887315),
 ([[1830, 20], [1858, 20], [1858, 46], [1830, 46]], '0', 0.5641889117560481),
 ([[12, 94], [36, 94], [36, 118], [12, 118]], '3', 0.934906657989373),
 ([[53, 95], [159, 95], [159, 115], [53, 115]],
  'Device Status',
  0.8130415432182342),
 ([[272, 92], [478, 92], [478, 118], [272, 118]],
  'Device Information',
  0.910271829568761),
 ([[276, 146], [392, 146], [392, 166], [276, 166]],
  'Personalization',
  0.999988826908191),
 ([[819, 149], [881, 149], [881, 167], [819, 167]],
  'Network',
  0.9999802199681402),
 ([[52, 158], [184, 158], [184, 182], [52, 182]],
  'Configure Device',
  0.9991724209596137),
 ([[291, 179], [339, 179], [339, 193], [291, 193]],
  'SERIAL',
  0.9763052406533913),
 ([[833, 179], [869, 179], [869, 193], [833, 193]],
  'DHCP',
  0.8482540249824524),
 ([[291, 203], [423, 203], [423, 223], [291, 223]],
  '30100000092096',
  0.9562319463663298),
 ([[831, 203], [867, 203], [867, 223], [831, 223]], 'YES', 0.9999124544578184),
 ([[53, 223], [141, 223], [141, 243], [53, 243]],
  'Device Info',
  0.7519944823110576),
 ([[293, 251], [329, 251], [329, 265], [293, 265]],
  'CSSN',
  0.9978789687156677),
 ([[291, 275], [423, 275], [423, 295], [291, 295]],
  '30100000092096',
  0.9580601377055338),
 ([[831, 275], [931, 275], [931, 295], [831, 295]],
  '10.27.15.166',
  0.8342315097597847),
 ([[52, 286], [166, 286], [166, 310], [52, 310]],
  'Device Update',
  0.9999955695892289),
 ([[291, 323], [323, 323], [323, 337], [291, 337]], 'MAC', 0.9976210125680953),
 ([[831, 323], [871, 323], [871, 337], [831, 337]], 'MASK', 0.94972825050354),
 ([[50, 349], [96, 349], [96, 375], [50, 375]], 'Logs', 0.9999788999557495),
 ([[291, 347], [437, 347], [437, 367], [291, 367]],
  '00.20-1BBA:O2.DB',
  0.5776305016951331),
 ([[829, 347], [939, 347], [939, 367], [829, 367]],
  '255.255.255.0',
  0.7491516691980197),
 ([[833, 395], [895, 395], [895, 411], [833, 411]],
  'GATEWAY',
  0.9811083618736438),
 ([[53, 415], [103, 415], [103, 435], [53, 435]], 'About', 0.9999817672712518),
 ([[831, 419], [931, 419], [931, 439], [831, 439]],
  '10.27.15.255',
  0.8677760559802672),
 ([[279, 493], [405, 493], [405, 511], [279, 511]],
  'Software Version',
  0.9292837145889874),
 ([[291, 523], [339, 523], [339, 537], [291, 537]],
  'XOVER',
  0.9553591061290474),
 ([[291, 549], [333, 549], [333, 567], [291, 567]],
  '1,.0.0',
  0.4632226501231506),
 ([[291, 593], [391, 593], [391, 609], [291, 609]],
  'XOVER SERVER',
  0.9768623794680419),
 ([[293, 621], [333, 621], [333, 639], [293, 639]],
  '0.1.0',
  0.9466661536950008),
 ([[291, 665], [379, 665], [379, 681], [291, 681]],
  'NANOCDN RR',
  0.9939162171960152),
 ([[291, 691], [423, 691], [423, 711], [291, 711]],
  'v2.4.2-trunk-4286',
  0.7006085442402246),
 ([[291, 737], [395, 737], [395, 753], [291, 753]],
  'NANOCDN CORE',
  0.8531056520251064),
 ([[290, 762], [608, 762], [608, 786], [290, 786]],
  'v2.4.2-trunk@4286, BkStbA 2.2.0 - API 6.7',
  0.7750610980209846),
 ([[615, 763], [685, 763], [685, 783], [615, 783]],
  'SVN 775',
  0.9954304513942291),
 ([[291, 811], [343, 811], [343, 825], [291, 825]],
  'KERNEL',
  0.999824260033197),
 ([[293, 835], [369, 835], [369, 855], [293, 855]],
  '4.19.127+',
  0.7441245501363044)]

In [42]:
import numpy as np
arr = np.array(output)
x,y,z = arr.T

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

In [43]:
print(x,y,z)

[list([[25, 13], [223, 13], [223, 55], [25, 55]])
 list([[973, 17], [1173, 17], [1173, 55], [973, 55]])
 list([[1794, 20], [1822, 20], [1822, 46], [1794, 46]])
 list([[1830, 20], [1858, 20], [1858, 46], [1830, 46]])
 list([[12, 94], [36, 94], [36, 118], [12, 118]])
 list([[53, 95], [159, 95], [159, 115], [53, 115]])
 list([[272, 92], [478, 92], [478, 118], [272, 118]])
 list([[276, 146], [392, 146], [392, 166], [276, 166]])
 list([[819, 149], [881, 149], [881, 167], [819, 167]])
 list([[52, 158], [184, 158], [184, 182], [52, 182]])
 list([[291, 179], [339, 179], [339, 193], [291, 193]])
 list([[833, 179], [869, 179], [869, 193], [833, 193]])
 list([[291, 203], [423, 203], [423, 223], [291, 223]])
 list([[831, 203], [867, 203], [867, 223], [831, 223]])
 list([[53, 223], [141, 223], [141, 243], [53, 243]])
 list([[293, 251], [329, 251], [329, 265], [293, 265]])
 list([[291, 275], [423, 275], [423, 295], [291, 295]])
 list([[831, 275], [931, 275], [931, 295], [831, 295]])
 list([[52, 286], [166, 286], [166, 310], [52, 310]])
 list([[291, 323], [323, 323], [323, 337], [291, 337]])
 list([[831, 323], [871, 323], [871, 337], [831, 337]])
 list([[50, 349], [96, 349], [96, 375], [50, 375]])
 list([[291, 347], [437, 347], [437, 367], [291, 367]])
 list([[829, 347], [939, 347], [939, 367], [829, 367]])
 list([[833, 395], [895, 395], [895, 411], [833, 411]])
 list([[53, 415], [103, 415], [103, 435], [53, 435]])
 list([[831, 419], [931, 419], [931, 439], [831, 439]])
 list([[279, 493], [405, 493], [405, 511], [279, 511]])
 list([[291, 523], [339, 523], [339, 537], [291, 537]])
 list([[291, 549], [333, 549], [333, 567], [291, 567]])
 list([[291, 593], [391, 593], [391, 609], [291, 609]])
 list([[293, 621], [333, 621], [333, 639], [293, 639]])
 list([[291, 665], [379, 665], [379, 681], [291, 681]])
 list([[291, 691], [423, 691], [423, 711], [291, 711]])
 list([[291, 737], [395, 737], [395, 753], [291, 753]])
 list([[290, 762], [608, 762], [608, 786], [290, 786]])
 list([[615, 763], [685, 763], [685, 783], [615, 783]])
 list([[291, 811], [343, 811], [343, 825], [291, 825]])
 list([[293, 835], [369, 835], [369, 855], [293, 855]])] ['SMAREDTV' 'XOverABR' '0' '0' '3' 'Device Status' 'Device Information'
 'Personalization' 'Network' 'Configure Device' 'SERIAL' 'DHCP'
 '30100000092096' 'YES' 'Device Info' 'CSSN' '30100000092096'
 '10.27.15.166' 'Device Update' 'MAC' 'MASK' 'Logs' '00.20-1BBA:O2.DB'
 '255.255.255.0' 'GATEWAY' 'About' '10.27.15.255' 'Software Version'
 'XOVER' '1,.0.0' 'XOVER SERVER' '0.1.0' 'NANOCDN RR' 'v2.4.2-trunk-4286'
 'NANOCDN CORE' 'v2.4.2-trunk@4286, BkStbA 2.2.0 - API 6.7' 'SVN 775'
 'KERNEL' '4.19.127+'] [0.5913040883835136 0.9995070422733559 0.9771506309887315
 0.5641889117560481 0.934906657989373 0.8130415432182342 0.910271829568761
 0.999988826908191 0.9999802199681402 0.9991724209596137
 0.9763052406533913 0.8482540249824524 0.9562319463663298
 0.9999124544578184 0.7519944823110576 0.9978789687156677
 0.9580601377055338 0.8342315097597847 0.9999955695892289
 0.9976210125680953 0.94972825050354 0.9999788999557495 0.5776305016951331
 0.7491516691980197 0.9811083618736438 0.9999817672712518
 0.8677760559802672 0.9292837145889874 0.9553591061290474
 0.4632226501231506 0.9768623794680419 0.9466661536950008
 0.9939162171960152 0.7006085442402246 0.8531056520251064
 0.7750610980209846 0.9954304513942291 0.999824260033197
 0.7441245501363044]

In [61]:
i  = 0
for wrd in y:
  print(i)
  print(wrd)
  concat = wrd
  file =  open("extractedText.txt", "a")
  file.write("\n")
  file.write(concat)
  i += 1
  file.close

0
SMAREDTV
1
XOverABR
2
0
3
0
4
3
5
Device Status
6
Device Information
7
Personalization
8
Network
9
Configure Device
10
SERIAL
11
DHCP
12
30100000092096
13
YES
14
Device Info
15
CSSN
16
30100000092096
17
10.27.15.166
18
Device Update
19
MAC
20
MASK
21
Logs
22
00.20-1BBA:O2.DB
23
255.255.255.0
24
GATEWAY
25
About
26
10.27.15.255
27
Software Version
28
XOVER
29
1,.0.0
30
XOVER SERVER
31
0.1.0
32
NANOCDN RR
33
v2.4.2-trunk-4286
34
NANOCDN CORE
35
v2.4.2-trunk@4286, BkStbA 2.2.0 - API 6.7
36
SVN 775
37
KERNEL
38
4.19.127+

In [91]:
i = 0
for coor in x:
  print(i)
  print(coor)
  concat = coor
  file =  open("extractedCoordinates.txt", "a")
  file.write("\n")
  file.write(str(concat))
  i += 1
  file.close

ValueError: ignored

In [68]:
import pandas as pd
df = pd.read_csv("/content/extractedText.txt")
df.head()

       Text
0  SMAREDTV
1  XOverABR
2         0
3         0
4         3

In [95]:
df1 = pd.read_csv("/content/extractedcoordinates.txt")
df1.head()

                                            co-ordinates
[[25    13]  [223   13]  [223   55]   [25           55]]
[[973   17]  [1173  17]  [1173  55]   [973          55]]
[[1794  20]  [1822  20]  [1822  46]   [1794         46]]
[[1830  20]  [1858  20]  [1858  46]   [1830         46]]
[[12    94]  [36    94]  [36    118]  [12          118]]

In [87]:
df1.to_csv('extractedCoordinates.csv')

In [96]:
frames = [df, df1]
new_df = df1.append(df, ignore_index=True)
new_df.head()

  co-ordinates Text
0         55]]  NaN
1         55]]  NaN
2         46]]  NaN
3         46]]  NaN
4        118]]  NaN

In [93]:
new_df

,co-ordinates,Text
"([[25,, 13],, [223,, 13],, [223,, 55],, [25,)",55]],NaN
"([[973,, 17],, [1173,, 17],, [1173,, 55],, [973,)",55]],NaN
"([[1794,, 20],, [1822,, 20],, [1822,, 46],, [1794,)",46]],NaN
"([[1830,, 20],, [1858,, 20],, [1858,, 46],, [1830,)",46]],NaN
"([[12,, 94],, [36,, 94],, [36,, 118],, [12,)",118]],NaN
...,...,...
34,NaN,NANOCDN CORE
35,NaN,v2.4.2-trunk@4286-BkStbA 2.2.0 - API 6.7
36,NaN,SVN 775
37,NaN,KERNEL
38,NaN,4.19.127+

In [97]:
new_df.to_csv('dummy.csv')

In [98]:
df.to_csv('extractedText.csv')